version: "3.1"

services:
  shieldy:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - wait-dependencies
  mongo:
    image: mongo
    restart: always
    env_file: .env
    volumes:
      - dbdata:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  wait-dependencies:
    image: willwill/wait-for-it:latest
    depends_on:
      - mongo
    entrypoint: /bin/sh
    command: >
      -c "./wait-for-it.sh mongo:27017 --strict --timeout=1"
  # If database debugging is needed
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   depends_on:
  #     - mongo
volumes:
  dbdata:
